# Generated by Django 4.2.5 on 2023-09-15 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='highscore',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
