# Generated by Django 4.2.5 on 2023-09-20 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_credentials'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credentials',
            name='email_otp',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
