# Generated by Django 4.2.5 on 2023-09-21 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0008_alter_credential_email_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.DeleteModel(
            name='Credential',
        ),
    ]
