# Generated by Django 4.2.5 on 2023-09-21 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0009_profile_email_otp_delete_credential'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_verified',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
