# Generated by Django 4.2.5 on 2023-09-22 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0010_profile_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
