# Generated by Django 4.2.5 on 2023-09-24 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0004_thread_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='thread',
            old_name='users',
            new_name='thread_users',
        ),
        migrations.AddField(
            model_name='thread',
            name='thread_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
