# Generated by Django 4.2.5 on 2023-09-24 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0006_rename_thread_users_thread_users_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='thread',
            name='thread_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
